---
title: Rockstat clickhouse writer
rpc:
  name: chwriter
  listen_all: true
  listen_direct: true

log:
  use: pino
  pino:
    safe: true
    level: <%= env.LOG_LEVEL || 'info' %>
    prettyPrint: false

redis:
  dsn: <%= env.REDIS_DSN %>

clickhouse:
  enabled: true
  dsn: <%= env.CHP_DSN %>
  #seconds
  uploadInterval: 5
  sync: true
  emergency_dir: ./emergency

metrics:
  statsd:
    host: <%= env.STATSD_HOST || '127.0.0.1' %>
    port: 8125
    debug: false
    prefix: krn
