---
clickhouse:
  # which props from base message should be copied
  copy_props: ['channel', 'uid', 'name', 'service', 'projectId', 'td']
  # events distribution. Format <event service>/<event name>:<table>
  destinations:
    track/default: events
    track/activity: activity
    track/scroll: activity
    other: webhooks

  # common tables columnts
  # all tables by default implements this cols
  base:
    # unique event id
    id: UInt64
    # rockstat user id
    uid: UInt64
    # event date (UTC, server time)
    date: Date
    # event datetime (UTC, server time)
    dateTime: DateTime
    # event timestamp (server time)
    timestamp: UInt64
    # received via
    channel: String
    # rockstat project id (receives from with event)
    projectId: UInt32
    # event name
    name: String
    # event dependend service
    service: String
    # transport data / ip
    td_ip: String
    # transport data / user agent
    td_ua: String
    # simple fingerprint based on IP and UserAgent
    td_fpid: UInt64
    # referer given from http transport layer
    td_ref: String
    # extra transport data
    td_extra.key: Array(String)
    td_extra.value: Array(String)

  # tables structure
  # common tables structrute. Can be omited by custom config
  tables:
    webhooks:
      extra.key: Array(String)
      extra.value: Array(String)
      _options:
        engine: MergeTree(date, (service, name, date), 8192)
    events:
      # full page url
      page_url: String
      # page referrer
      page_ref: String
      # page title
      page_title: String
      # domain/hostname of browsed page
      page_domain: String
      # http/https/etc
      page_scheme: Enum8('' = 0, 'http' = 1, 'https' = 2, 'other' = 3, 'ws' = 4)
      # marketing marks
      page_query_utm_source: String
      page_query_utm_campaign: String
      page_query_utm_medium: String
      page_query_utm_content: String
      page_query_utm_term: String
      page_query_gclid: String
      page_query_yclid: String
      # extra query params
      page_query_extra.key: Array(String)
      page_query_extra.value: Array(String)
      # session type: (campaign/organic/referral/direct/internal/social)
      sess_type: String
      # search/social/ads engine
      sess_engine: String
      # user session number
      sess_num: UInt16
      # marks flag
      sess_hasMarks: UInt8
      # page number in current session
      sess_pageNum: UInt16
      # event number in current session
      sess_eventNum: UInt16
      # marketing marks
      sess_marks_utm_source: String
      sess_marks_utm_campaign: String
      sess_marks_utm_medium: String
      sess_marks_utm_content: String
      sess_marks_utm_term: String
      sess_marks_has_gclid: Int8 DEFAULT -1
      sess_marks_has_yclid: Int8 DEFAULT -1
      # extra marks
      sess_marks_extra.key: Array(String)
      sess_marks_extra.value: Array(String)
      # session start timestamp
      sess_start: UInt64
      # referrer hostname (without www)
      sess_refhost: String
      # library indentificator
      lib_id: String
      # library version
      lib_v: Float32
      # library snippet version
      lib_sv: Float32
      # scroll doc height
      scroll_dh: UInt16
      # scroll client height
      scroll_ch: UInt16
      # scroll top offset pixels
      scroll_to: Int32 # can be ne
      # current scroll (persents)
      scroll_cs: UInt16
      # max scroll (persents)
      scroll_ms: UInt16
      # iframe detection
      browser_if1: Int8
      browser_if2: Int8
      # browser width
      browser_w: Int16
      # browser height
      browser_h: Int16
      # browser total width
      browser_tw: Int16
      # browser total height
      browser_th: Int16
      # browser available width
      browser_aw: Int16
      # browser available height
      browser_ah: Int16
      # screen.orientation.devicePixelRatio
      browser_sopr: Int16
      # screen.orientation.angle
      browser_soa: Int16
      # screen.orientation.type
      browser_sot: String
      # navigator.platform
      browser_plt: String
      # navigator.product
      browser_prd: String
      # sypex geo cols
      sxgeo_country_iso: String
      sxgeo_country_ru: String
      sxgeo_country_en: String
      sxgeo_region_iso: String
      sxgeo_region_ru: String
      sxgeo_region_en: String
      sxgeo_city_ru: String
      sxgeo_city_en: String
      # maxmins geo cols
      mmgeo_country_iso: String
      mmgeo_country_ru: String
      mmgeo_country_en: String
      mmgeo_region_iso: String
      mmgeo_region_ru: String
      mmgeo_region_en: String
      mmgeo_city_ru: String
      mmgeo_city_en: String
      # user agent parser cols
      uaparser_is_bot: Int8
      uaparser_is_mob: Int8
      uaparser_is_tablet: Int8
      uaparser_is_pc: Int8
      uaparser_browser_family: String
      uaparser_browser_version: Array(Int16)
      uaparser_os_family: String
      uaparser_os_version: Array(Int16)
      uaparser_device_family: String
      uaparser_device_brand: String
      uaparser_device_model: String
      # timezone name
      user_tz: String
      # timestamp
      user_ts: UInt64
      # timezone offset * 1000
      user_tzo: Int32
      # id (user id from website that uses rockstat)
      user_id: String
      # google analytics client id
      user_gaId: String
      # yandex metrika client id
      user_ymId: String
      # custom user traits
      user_extra.key: Array(String)
      user_extra.value: Array(String)
      # extra data fields
      data_extra.key: Array(String)
      data_extra.value: Array(String)
      # LocalStorage
      char_ls: Int16 DEFAULT -1
      # document.addEventListener
      char_ae: Int16 DEFAULT -1
      # Promise
      char_pr: Int16 DEFAULT -1
      # sendBeacon
      char_sb: Int16 DEFAULT -1
      # atob
      char_ab: Int16 DEFAULT -1
      # web-push
      char_wp: Int16 DEFAULT -1
      # (browser performance metrics)
      # timing.connectStart (reference point, always 0)
      perf_cs: Int16
      # timing.secureConnectionStart (num / -1)
      perf_scs: Int16
      # timing.domLoading
      perf_dl: Int16
      # timing.domComplete (num / -1)
      perf_dc: Int16
      # timing.domInteractive
      perf_di: Int16
      # timing.requestStart
      perf_rqs: Int16
      # timing.responseStart
      perf_rss: Int16
      # timing.responseEnd
      perf_rse: Int16
      # timing.connectEnd
      perf_ce: Int16
      ### table options
      _options:
        engine: MergeTree(date, (intHash32(uid), date), 8192)

    activity:
      _options:
        extend: events

    telegram:
      chat_id: Int64
      chat_type: String
      from_first_name: String
      from_id: UInt64
      from_is_bot: UInt8
      from_language_code: String
      from_username: String
      text: String
      message_id: UInt64
      update_id: String
      _options:
        extend: webhooks

    logs:
      # unique event id
      id: UInt64
      # event date (UTC, server time)
      date: Date
      # event datetime (UTC, server time)
      dateTime: DateTime
      # source service
      service: String
      # stdout / stderr
      source: String
      # standard level number 10=debug 20=info etc..]
      level: Int8
      # name of level
      levelName: String
      # logger name
      logger: String
      # message part
      message: String
      # structured data part
      data: String
      _options:
        engine: MergeTree(date, (source, date, level), 8192)
