---
writers:
  clickhouse:
    enabled: true
    dsn: <%= env.CH_DSN %>
    uploadInterval: 2 #seconds
    sync: true
    # data distribution
    alcojs:
      default: events_v2
      activity: activity
      scroll: activity
    webhook:
      default: webhooks_v2
      test/test: wh_test_test
    pixel:
      default: events_v2
      checkid: id_checks
    # common tables fields
    base:
      id: UInt64
      date: Date
      dateTime: DateTime
      timestamp: UInt64
      channel: Enum8('' = 0, 'other' = 1, 'alcojs' = 5, 'webhook' = 6, 'pixel' = 7, 'r1' = 8 , 'r2' = 9, 'r3' = 10)
      projectId: UInt32
      name: String
    tables:
      webhooks_v2:
        service: String
        action: String
        remote_ip: String
        data.key: Array(String)
        data.value: Array(String)
        _options:
          engine: MergeTree(date, (service, action, date), 8192)
      id_checks:
        uid: UInt64
        data_gaId: String
        data.key: Array(String)
        data.value: Array(String)
        _options:
          engine: MergeTree(date, (uid, date), 8192)
      events_v2:
        uid: UInt64
        ip: String
        userAgent: String
        page_url: String
        page_referrer: String
        page_title: String
        page_domain: String
        page_proto: Enum8('' = 0, 'http' = 1, 'https' = 2, 'other' = 3)
        page_query_utm_source: String
        page_query_utm_campaign: String
        page_query_utm_medium: String
        page_query_utm_content: String
        page_query_utm_term: String
        page_query_gclid: String
        page_query_yclid: String
        page_query.key: Array(String)
        page_query.value: Array(String)
        session_type: String
        session_engine: String
        session_num: UInt16
        session_hasMarks: UInt8
        session_pageNum: UInt16
        session_eventNum: UInt16
        session_marks_utm_source: String
        session_marks_utm_campaign: String
        session_marks_utm_medium: String
        session_marks_utm_content: String
        session_marks_utm_term: String
        session_marks_has_gclid: Int8 DEFAULT -1
        session_marks_has_yclid: Int8 DEFAULT -1
        session_marks.key: Array(String)
        session_marks.value: Array(String)
        session_start: UInt64
        session_refHost: String
        lib_name: String
        lib_libver: UInt32
        lib_snippet: UInt32
        client_tz: String
        client_ts: UInt64
        client_tzOffset: Int32
        client_platform: String
        client_product: String
        browser_if: Array(UInt8)
        browser_wh_w: UInt16
        browser_wh_h: UInt16
        browser_sr_tot_w: UInt16
        browser_sr_tot_h: UInt16
        browser_sr_avail_w: UInt16
        browser_sr_avail_h: UInt16
        browser_sr_asp: UInt16
        browser_sr_oAngle: UInt16
        browser_sr_oType: String
        sxg_country_iso: String
        sxg_country_name_ru: String
        sxg_country_name_en: String
        sxg_region_iso: String
        sxg_region_name_ru: String
        sxg_region_name_en: String
        sxg_city_id: UInt32
        sxg_city_name_ru: String
        sxg_city_name_en: String
        mdd_isBot: Int8
        mdd_client_type: String
        mdd_client_name: String
        mdd_client_version: String
        mdd_os_name: String
        mdd_os_version: String
        mdd_os_platform: String
        mdd_device_type: String
        mdd_device_brand: String
        mdd_device_model: String
        user_id: String
        user_gaId: String
        user_ymId: String
        user_traits.key: Array(String)
        user_traits.value: Array(String)
        data.key: Array(String)
        data.value: Array(String)
        scroll_docHeight: UInt16
        scroll_clientHeight: UInt16
        scroll_topOffset: Int32 # can be ne
        scroll_scroll: UInt16
        scroll_maxScroll: UInt16
        cf_locstor: Int16 DEFAULT -1
        cf_addel: Int16 DEFAULT -1
        cf_promise: Int16 DEFAULT -1
        cf_sbeacon: Int16 DEFAULT -1
        cf_atob: Int16 DEFAULT -1
        cf_wpush: Int16 DEFAULT -1
        perf_ce: Int16
        perf_cs: Int16
        perf_dc: Int16
        perf_di: Int16
        perf_dl: Int16
        perf_rqs: Int16
        perf_rse: Int16
        perf_rss: Int16
        perf_scs: Int16
        _options:
          engine: MergeTree(date, (intHash32(uid), date), 8192)

      activity:
        _options:
          extend: events_v2
